name: My First Workflow

on: push

jobs:
  run-emotion-script:
    runs-on: ubuntu-latest

    steps:
    - name: ĞšĞ»Ğ¾Ğ½Ğ¸Ñ€Ğ¾Ğ²Ğ°Ñ‚ÑŒ Ñ€ĞµĞ¿Ğ¾Ğ·Ğ¸Ñ‚Ğ¾Ñ€Ğ¸Ğ¹
      uses: actions/checkout@v3

    - name: Ğ£ÑÑ‚Ğ°Ğ½Ğ¾Ğ²Ğ¸Ñ‚ÑŒ Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Ğ—Ğ°Ğ¿ÑƒÑÑ‚Ğ¸Ñ‚ÑŒ Python-ĞºĞ¾Ğ´
      run: |
        import random
        emotions = ["ğŸ˜„", "ğŸ˜‚", "ğŸ¤“", "ğŸ˜", "ğŸ¥³", "ğŸ¤–"]
        print("Hello, world!!! Today I feel like", random.choice(emotions))
